### PR TITLE
Cmake fixes for v0.8.3

### PR DESCRIPTION
**Pull request by saukijan**
This PR is based on various CI reports form [conan-central-index](https://github.com/conan-io/conan-center-index/pull/2009). These changes include: 

Root CMakeLists.txt
* change `mdnsd -> mdnsd_example` and `mdnsd  -> mdns_daemon` to avoid name collision on windows systems, solves errors in [CMake.log](https://c3i.jfrog.io/c3i/misc/logs/pr/2009/19/pro-mdnsd/0.8.3/f27dcd2d5e453cb01f9324a959461903ce8116a0/create_stdout.txt)
* remove `BUILD_SHARED_LIBS_DEFAULT` option, since `BUILD_SHARED_LIBS` is enought on it's own

libmdnsd CMakeLists.txt
* `set_property -> target_compile_definitions` to properly set windows export symbols, solves errors in [CMake.log](https://c3i.jfrog.io/c3i/misc/logs/pr/2009/18/pro-mdnsd/0.8.3/f27dcd2d5e453cb01f9324a959461903ce8116a0/create_stdout.txt)
* rework `mdnsd_config.h.in` into `mdnsd_config.h`, solves msvc 15 not compiling **.lib** file for the **.dll** when `shared=True`, solves erros in [CMake.log](https://c3i.jfrog.io/c3i/misc/logs/pr/2009/33/pro-mdnsd/0.8.3/ff82a1e70ba8430648a79986385b20a3648f8c19/create_stdout.txt) 
* moved `MDNSD_LOGLEVEL` definition from  `mdnsd_config.h` into **CMakeLists.txt**
* changed project name `libmdnsd -> mdnsd`
* changed target names to use the project name
* changed include directory install location to `${CMAKE_INSTALL_INCLUDEDIR}/lib${PROJECT_NAME}` to support include path `libmdnsnd/*`

### CODE REVIEW

**Comment by Pro** [comment]
Thanks!
Can you rebase your branch instead of merging master. That makes the gith history more linear. And if possible also clean up the git messages

**Comment by saukijan** [comment]
I am not sure how to re-base my master branch without loosing my work. Could you tell how you do it?

**Comment by saukijan** [comment]
Also **CI AppVeyor** jobs use Solution files `.sln` for MSVC setups, instead of `CMakeLists.txt`, thus failing. Is that intended?

**Comment by Pro** [comment]
In general, PRs should not be created based on master.

Best option now is to create a new branch from your current state `git checkout -b new_stuff` , rebase and then create a new PR based on that branch.
Or you force push that new branch onto your master

**Comment by Pro** [comment]
Appveyor is using cmake to create a VS project, so that is intended and the default way. Not sure why it is failing here

**Comment by Pro** [comment]
Probably the line `msbuild mdnsd.sln /m` in appveyor.yml needs to be changed to libmdnsd.yml or to use the cmake build command. Feel free to upade this.

**Comment by saukijan** [comment]
moved to https://github.com/Pro/mdnsd/pull/22

**Pull request closed without merging**
